-- ============================================
-- SEED RECIPE LIBRARY WITH SAMPLE RECIPES
-- ============================================

-- Insert sample approved recipes for the community
INSERT INTO recipes (
  title,
  author_name,
  description,
  ingredients,
  instructions,
  scripture,
  scripture_reference,
  meditation,
  prep_time,
  cook_time,
  servings,
  cuisine,
  meal_type,
  dietary_tags,
  status,
  is_featured,
  approved_at
) VALUES 
(
  'Blessed Breakfast Bowl',
  'Temple Keepers Team',
  'Start your day with this nourishing bowl filled with whole grains, fresh fruits, and nuts. A breakfast that honors the temple of your body.',
  ARRAY[
    '1 cup cooked quinoa or oatmeal',
    '1/2 cup Greek yogurt',
    '1 banana, sliced',
    '1/4 cup mixed berries',
    '2 tablespoons almonds, chopped',
    '1 tablespoon honey',
    '1 teaspoon chia seeds',
    'Pinch of cinnamon'
  ],
  ARRAY[
    'Cook quinoa or oatmeal according to package directions and let cool slightly',
    'In a bowl, place the cooked grains as the base',
    'Add a dollop of Greek yogurt on top',
    'Arrange banana slices and berries around the bowl',
    'Sprinkle with chopped almonds and chia seeds',
    'Drizzle honey over the top',
    'Dust with cinnamon and serve immediately'
  ],
  'So whether you eat or drink or whatever you do, do it all for the glory of God.',
  '1 Corinthians 10:31',
  'As you prepare this nourishing bowl, remember that every healthy choice you make is an act of worship. Your body is a temple, fearfully and wonderfully made. Take time to be grateful for the abundance of whole foods that fuel your body and energize your spirit.',
  '10 minutes',
  '15 minutes',
  '1 serving',
  'American',
  'Breakfast',
  ARRAY['Vegetarian', 'Gluten-Free Option', 'Healthy'],
  'approved',
  true,
  NOW()
),
(
  'Peaceful Mediterranean Salad',
  'Temple Keepers Team',
  'A vibrant salad that brings together the best of Mediterranean flavors, perfect for a light lunch or dinner.',
  ARRAY[
    '4 cups mixed greens',
    '1 cucumber, diced',
    '1 cup cherry tomatoes, halved',
    '1/2 red onion, thinly sliced',
    '1/2 cup Kalamata olives',
    '1/2 cup feta cheese, crumbled',
    '1/4 cup extra virgin olive oil',
    '2 tablespoons lemon juice',
    '1 teaspoon dried oregano',
    'Salt and pepper to taste',
    '1/4 cup fresh parsley, chopped'
  ],
  ARRAY[
    'Wash and dry the mixed greens, place in a large bowl',
    'Add cucumber, cherry tomatoes, and red onion',
    'Toss in the Kalamata olives and crumbled feta cheese',
    'In a small bowl, whisk together olive oil, lemon juice, oregano, salt, and pepper',
    'Pour dressing over salad and toss gently to combine',
    'Garnish with fresh parsley',
    'Serve immediately and enjoy this healthy, Mediterranean delight'
  ],
  'The Lord is my shepherd, I lack nothing. He makes me lie down in green pastures, he leads me beside quiet waters.',
  'Psalm 23:1-2',
  'This salad reminds us of the green pastures and still waters mentioned in Psalm 23. As you eat, meditate on how God provides abundantly for our needs. Each fresh ingredient is a gift from creation, nourishing both body and soul.',
  '15 minutes',
  '0 minutes',
  '2-3 servings',
  'Mediterranean',
  'Lunch',
  ARRAY['Vegetarian', 'Gluten-Free', 'Keto-Friendly'],
  'approved',
  true,
  NOW()
),
(
  'Strength-Building Lentil Soup',
  'Temple Keepers Team',
  'A hearty, protein-rich soup that builds strength and warms the soul. Perfect for meal prep and freezes beautifully.',
  ARRAY[
    '2 tablespoons olive oil',
    '1 large onion, diced',
    '3 carrots, diced',
    '3 celery stalks, diced',
    '4 cloves garlic, minced',
    '1.5 cups dried green or brown lentils',
    '6 cups vegetable broth',
    '1 can (14oz) diced tomatoes',
    '2 bay leaves',
    '1 teaspoon cumin',
    '1 teaspoon turmeric',
    '1/2 teaspoon smoked paprika',
    'Salt and pepper to taste',
    '2 cups fresh spinach',
    'Fresh lemon juice for serving'
  ],
  ARRAY[
    'Heat olive oil in a large pot over medium heat',
    'Add onion, carrots, and celery. Sauté until softened, about 5-7 minutes',
    'Stir in garlic and cook for 1 minute until fragrant',
    'Add lentils, vegetable broth, diced tomatoes, bay leaves, cumin, turmeric, and paprika',
    'Bring to a boil, then reduce heat and simmer for 30-35 minutes until lentils are tender',
    'Remove bay leaves and stir in fresh spinach until wilted',
    'Season with salt and pepper to taste',
    'Serve hot with a squeeze of fresh lemon juice',
    'Store leftovers in the refrigerator for up to 5 days or freeze for up to 3 months'
  ],
  'He gives strength to the weary and increases the power of the weak.',
  'Isaiah 40:29',
  'This hearty soup is a reminder of God''s provision and strength. Lentils were a staple in biblical times, sustaining God''s people through their journeys. As you prepare and eat this soup, reflect on how God strengthens us daily, both physically and spiritually.',
  '15 minutes',
  '40 minutes',
  '6 servings',
  'Middle Eastern',
  'Dinner',
  ARRAY['Vegan', 'Gluten-Free', 'High-Protein'],
  'approved',
  false,
  NOW()
),
(
  'Grace-Filled Grilled Chicken',
  'Temple Keepers Team',
  'Simple, flavorful grilled chicken that celebrates whole, clean ingredients and nourishes your body.',
  ARRAY[
    '4 boneless, skinless chicken breasts',
    '3 tablespoons olive oil',
    '2 tablespoons lemon juice',
    '3 cloves garlic, minced',
    '1 teaspoon dried rosemary',
    '1 teaspoon dried thyme',
    '1/2 teaspoon paprika',
    '1 teaspoon salt',
    '1/2 teaspoon black pepper',
    'Fresh herbs for garnish'
  ],
  ARRAY[
    'In a bowl, mix olive oil, lemon juice, garlic, rosemary, thyme, paprika, salt, and pepper',
    'Place chicken breasts in a shallow dish or zip-lock bag',
    'Pour marinade over chicken, ensuring all pieces are well coated',
    'Marinate in refrigerator for at least 30 minutes, up to 4 hours',
    'Preheat grill or grill pan to medium-high heat',
    'Remove chicken from marinade and let excess drip off',
    'Grill chicken for 6-7 minutes per side until internal temperature reaches 165°F',
    'Let rest for 5 minutes before slicing',
    'Garnish with fresh herbs and serve with your favorite vegetables or salad'
  ],
  'Whether you eat or drink or whatever you do, do it all for the glory of God.',
  '1 Corinthians 10:31',
  'As you prepare this simple yet delicious meal, remember that even everyday acts like cooking can be done for God''s glory. The care you take in nourishing yourself and others is an expression of love and stewardship of the body God has given you.',
  '40 minutes (includes marinating)',
  '15 minutes',
  '4 servings',
  'American',
  'Dinner',
  ARRAY['High-Protein', 'Gluten-Free', 'Keto-Friendly', 'Paleo'],
  'approved',
  false,
  NOW()
),
(
  'Joyful Berry Smoothie',
  'Temple Keepers Team',
  'A refreshing, antioxidant-rich smoothie that brings joy to your morning and vitality to your day.',
  ARRAY[
    '1 cup mixed berries (strawberries, blueberries, raspberries)',
    '1 banana',
    '1 cup unsweetened almond milk',
    '1/2 cup Greek yogurt',
    '1 tablespoon almond butter',
    '1 tablespoon ground flaxseed',
    '1 teaspoon honey (optional)',
    '1/2 cup ice',
    'Fresh mint for garnish'
  ],
  ARRAY[
    'Add all ingredients to a high-speed blender',
    'Blend on high for 30-60 seconds until smooth and creamy',
    'Taste and adjust sweetness with honey if desired',
    'Pour into a glass',
    'Garnish with a few fresh berries and a sprig of mint',
    'Serve immediately and enjoy the burst of flavor and nutrients'
  ],
  'A cheerful heart is good medicine, but a crushed spirit dries up the bones.',
  'Proverbs 17:22',
  'This vibrant smoothie is a celebration of joy and health. The bright colors remind us of God''s beautiful creation and the abundance of nutrients He provides. As you drink, let gratitude and joy fill your heart, knowing that taking care of your health is an act of worship.',
  '5 minutes',
  '0 minutes',
  '1 serving',
  'American',
  'Breakfast',
  ARRAY['Vegetarian', 'Gluten-Free', 'Healthy'],
  'approved',
  false,
  NOW()
);

-- Confirm insertion
SELECT COUNT(*) as "Sample Recipes Added" FROM recipes WHERE status = 'approved';
